# Default values for enterprise-doc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets:
  - name: qn-registry-secret

image:
  repository: ccr.ccs.tencentyun.com/koderover-rc/zadig-x-doc
  tag: 20210517100133-8-main
