apiVersion: apps/v1
kind: Deployment
metadata:
  name: zadig-x-doc
  labels:
    {{- include "zadig.microservice.enterpriseDoc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zadig.microservice.enterpriseDoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zadig.microservice.enterpriseDoc.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: zadig-x-doc
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100M
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}