apiVersion: v1
kind: Service
metadata:
  name: cfapi
  labels:
    {{- include "zadig.microservice.collie.cfapi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "zadig.microservice.collie.cfapi.port" . }}
      targetPort: {{ include "zadig.microservice.collie.cfapi.port" . }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "zadig.microservice.collie.cfapi.selectorLabels" . | nindent 6 }}