apiVersion: v1
kind: Service
metadata:
  name: collie-server
  labels:
    {{- include "zadig.microservice.collie.server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "zadig.microservice.collie.server.port" . }}
      targetPort: {{ include "zadig.microservice.collie.server.port" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "zadig.microservice.collie.server.selectorLabels" . | nindent 4 }}