# Default values for clair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets:
  - name: qn-registry-secret

postgres:
  image:
    repository: ccr.ccs.tencentyun.com/koderover-public/library-postgres
    tag: "9.6"

replicas: 1
server:
  image:
    repository: ccr.ccs.tencentyun.com/koderover-rc/clair
    tag: v0.1.1
client:
  image:
    repository: ccr.ccs.tencentyun.com/koderover-rc/dockerscan
    tag: v0.1.3

registry:
  qnSecret: '{"auths":{"ccr.ccs.tencentyun.com":{"auth":"MTAwMDA5MDUyNzcyOllvdk5sMDdXbXc="}}}'


