apiVersion: v1
kind: ConfigMap
metadata:
  name: aslanx-config
  labels:
    {{- include "zadig.microservice.aslan-x.labels" . | nindent 4 }}
data:
  # --------------------------------------------------------------------------------------
  # logging
  # level: 0(Debug), 1(Info), 2(Warn), 3(Error), 4(Panic), 5(Fatal)
  # --------------------------------------------------------------------------------------
  LOG_LEVEL: Info

  # --------------------------------------------------------------------------------------
  # mongo
  # --------------------------------------------------------------------------------------
  MONGODB_CONNECTION_STRING: {{ .Values.mongodb.connectionString }}
  ASLAN_DB: {{ default "zadig" .Values.mongodb.db }}

  POETRY_API_ROOT_KEY: {{ include "zadig.rootToken" . }}

  S3STORAGE_ENDPOINT: {{ .Values.minio.endpoint }}
  S3STORAGE_AK: {{ .Values.minio.accessKey.password }}
  S3STORAGE_SK: {{ .Values.minio.secretKey.password }}
  S3STORAGE_BUCKET: {{ .Values.minio.bucket }}
  S3STORAGE_PROTOCOL: {{ .Values.minio.protocol }}

  SONAR_ROOT_TOKEN: admin:admin
