apiVersion: v1
kind: Service
metadata:
  name: aslanx
  labels:
    {{- include "zadig.microservice.aslan-x.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ template "zadig.microservice.aslan-x.port" . }}
      targetPort: {{ template "zadig.microservice.aslan-x.port" . }}
  selector:
    {{- include "zadig.microservice.aslan-x.selectorLabels" . | nindent 4 }}
