apiVersion: v1
kind: Service
metadata:
  name: clair
  labels:
    {{- include "zadig.microservice.clair.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: clair
      port: {{ include "zadig.microservice.clair.server.port" . }}
      targetPort: {{ include "zadig.microservice.clair.server.port" . }}
    - protocol: TCP
      name: clair-health
      port: {{ include "zadig.microservice.clair.server.healthPort" . }}
      targetPort: {{ include "zadig.microservice.clair.server.healthPort" . }}
    - protocol: TCP
      name: dockerscan
      port: {{ include "zadig.microservice.clair.client.port" . }}
      targetPort: {{ include "zadig.microservice.clair.client.port" . }}
  selector:
    {{- include "zadig.microservice.clair.selectorLabels" . | nindent 4 }}