apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "zadig.db.postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "zadig.db.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zadig.db.postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 512m
              memory: 1Gi
