apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    {{- include "zadig.microservice.sonar.qube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-80-9000
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    {{- include "zadig.microservice.sonar.qube.selectorLabels" . | nindent 4 }}
